[package]
name = "lit-coin"
version = "0.1.0"
authors = ["Fardeem Munir <munirfardeem@gmail.com>"]
edition = "2018"

[dependencies]
sha256 = "1.0.2"
chrono = "0.4"
secp256k1 = {version = "0.20.2", features = ["rand", "bitcoin_hashes"]}
rand = {version = "0.6", features = ["std"]}